--- 
user: www-data
group: www-data
pid: ~/app/il_dashboard/current/tmp/pids/thin.pid
timeout: 30
wait: 30
log: ~/app/il_dashboard/current/log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
threaded: true
no-epoll: true
daemonize: true
socket: ~/app/il_dashboard/current/tmp/sockets/thin.sock
chdir: ~/app/il_dashboard/current
tag: il_dashboard_server aux
