--- 
#user: lmis
#group: sudo
pid: /home/lmis/app/il_dashboard/current/tmp/pids/thin.pid
port: 5432
timeout: 30
wait: 30
log: /home/lmis/app/il_dashboard/current/log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
threaded: true
no-epoll: true
daemonize: true
socket: /home/lmis/app/il_dashboard/current/tmp/sockets/thin.sock
chdir: /home/lmis/app/il_dashboard/current
tag: il_dashboard_server aux
